services:
    dvdworld_user.registration.form.type:
        class: DvdWorld\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: dvdworld_user_registration }